apiVersion: v1
kind: ConfigMap
metadata:
  name: code-cm
  namespace: codens
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace -p 8443:8443
  PROXY_DOMAIN: code-188.166.206.179..nip.io

---
apiVersion: v1
kind: Secret
metadata:
  name: code-secret
  namespace: codens
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=
