apiVersion: apps/v1
kind: Deployment
metadata:
  name: codedb-deploy
  namespace: codens
  labels:
    app: code
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code
      tier: database
  template:
    metadata:
      name: codedb-po
      labels:
        app: bgg
        tier: database
    spec:
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: codedb-pvc
      containers:
        - name: bgg-container
          image: stackupiss/bgg-database:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: workspace-vol
              mountPath: /config/workspace

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
spec:
  type: ClusterIP
  selector:
    app: bgg
    tied: database
    name: bggdb-po
  ports:
    - port: 3306
      targetPort: 3306
