apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeapp-deploy
  namespace: codens
  labels:
    app: code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code
  template:
    metadata:
      name: codeapp-po
      namespace: codens
      labels:
        app: code
    spec:
      volumes:
        - name: workspace-vol
          persistentVolumeClaim:
            claimName: code-pvc
      containers:
        - name: codeapp-container
          image: linuxserver/code-server:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: code-cm
            - secretRef:
                name: code-secret
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: workspace-vol
              mountPath: /config/workspace

---
apiVersion: v1
kind: Service
metadata:
  name: codeapp-svc
  namespace: codens
  labels:
    app: code
spec:
  type: ClusterIP
  selector:
    app: code
  ports:
    - port: 8443
      targetPort: 8443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-ing
  namespace: codens
  labels:
    app: code
    name: code-ing
spec:
  ingressClassName: nginx
  rules:
    - host: code-188.166.206.179.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codeapp-svc
                port:
                  number: 8443
