---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bgg
    type: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgg
      type: app
  template:
    metadata:
      name: bggapp-po
      labels:
        app: bgg
        type: app
    spec:
      containers:
        - name: app-container
          image: stackupiss/bgg-backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          envFrom:
            - configMapRef:
                name: bgg-cm
            - secretRef:
                name: bgg-secret
---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bgg
    type: app
spec:
  type: NodePort
  selector:
    app: bgg
    type: app
  ports:
    - port: 8080
      targetPort: 3000
