---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  namespace: myns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dov
      dept: eng
  template:
    metadata:
      name: dov-po
      labels:
        app: dov
        dept: eng
    spec:
      containers:
        - name: dov-container
          image: chukmunnlee/dov-bear:v5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: INSTANCE_NAME
              value: dov-bear
            - name: INSTANCE_HASH
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          livenessProbe:
            httpGet:
              path: /heathz
              port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: myns
spec:
  type: ClusterIP
  selector:
    app: dov
    dept: eng
  ports:
    - port: 8080
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dov-ing
  namespace: myns
  labels:
    app: dov
    name: dov-ing
spec:
  ingressClassName: nginx
  rules:
    - host: dov-10.245.140.191.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: dov-svc
              port:
                number: 8080
